const express = require('express')
const app = express()
var bodyParser = require('body-parser')

const port = process.env.PORT||3000
const router=require('./Routes/routes')
const category=require('./Routes/category')
const product=require('./Routes/product')
const dashboard=require('./Routes/dashboard')
const bill=require('./Routes/bill')
const connection=require('./connection')
var cors = require('cors')
app.set('view engine','ejs')
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use('/routes',router)
app.use('/category',category)
app.use('/product',product)
app.use('/bill',bill)
app.use('/dashboard',dashboard)
app.get('/', (req, res) => {
  res.send('Hello World!')
})
app.listen(port)